const catchingError = () => {}

module.exports = catchingError;